baseURL = 'https://j03wh1t3.com'
languageCode = 'en-GB'
title = 'Joe White - Resume'
theme = 'hugo-resume'

[author]
  name = 'Joe White'
  homepage = '/about'

[params]
# Personal Information
address = "Leeds, UK"
email = "joe1997white@gmail.com"
firstName = "Joe"
lastName = "White"
phone = "+447467438927"
profileImage = "img/mugShot.jpg"  # Place in static/img/
favicon = "/favicon.ico"

# Display Options
showContact = true          # Show contact section
showCertifications = false  # Show certifications
showSocializations = true  # Show social media links

# Sections to display (in order)
sections = ["skills", "experience", "education"]

# Social Media Handles
[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/joe-white-aba9a1202/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/J03white"

# Display Options
# showQr = true               # Show QR code for contact info
showContact = false          # Show contact section
showCertifications = true  # Show certifications
showSocializations = true  # Show social media links



# Code highlighting settings
enableGitInfo = false

# Required output formats
[outputs]
home = ["HTML", "JSON"]

# Required taxonomies
[taxonomies]
tag = "tags"

