baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'Joe White - Resume'
theme = 'hugo-resume'


[params]
# Personal Information
address = "Leeds, UK"
email = "joe1997white@gmail.com"
firstName = "Joe"
lastName = "White"
phone = "+447467438927"
profileImage = "img/mugShot.jpg"  # Place in static/img/
favicon = "/favicon.ico"


# Social Media Handles
[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/joe-white-aba9a1202/"

# Display Options
# showQr = true               # Show QR code for contact info
showContact = true          # Show contact section
showCertifications = true  # Show certifications
showSocializations = true  # Show social media links

# Sections to display (in order)
sections = ["skills", "experience", "education"]

# Code highlighting settings
enableGitInfo = false

# Required output formats
[outputs]
home = ["HTML", "JSON"]

# Required taxonomies
[taxonomies]
tag = "tags"
